name: Render Electronics

on:
  push:
  workflow_dispatch:

jobs:
  render-schematic:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: ./electronics/scripts/dependencies.sh

