name: Render Electronics

on:
  push:
  workflow_dispatch:

jobs:
  render-schematic:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
